# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  npm-pipedrive:
    type: npm-registry
    url: https://npm-registry-proxy.pipedrive.tools
    token: ${{ secrets.NPM_TOKEN }}
  git-pipedrive:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GHA_ACCESS_TOKEN}}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '10:45'
      timezone: 'Europe/Tallinn'
    rebase-strategy: 'disabled'
    registries:
      - npm-pipedrive
      - git-pipedrive