import { getAuthorizationUrl, initAPIClient } from '../../../shared/oauth';

// Redirect the user to the authorization URL generated by the client
export const handler = (req, res) => {
  const client = initAPIClient({});
  res.redirect(getAuthorizationUrl(client));
};
